### PR TITLE
Nuget and Indicator Update

### PR DESCRIPTION
**Pull request by ParthMandalia**
Updated Nugets
1. Microsoft.NETCore.UniversalWindowsPlatrofm to last stable Version
2. Uno.Microsoft.Toolkit to support Uno Platform to latest Preview Version

Updated Polygon with Path to Match the OuterDiameter.

I was experimenting in the Demo Project. Only update Nuget refrence in those.

Need Nuget package for use in my Uno platform.

Thanks

### CODE REVIEW

**Comment by porrey** [comment]
Thanks for the updates.

After reviewing the code, I went a different way with the change to the indicator arrow you made. The flat top was intentional but made me realize it should be customizable. I create an updated version that allows the indicator arrow to be replaced in the control's XAML. I will also publish a pre-release version of the package using the Uno version of the framework. The XAML can be entered as follows:

```
<colorpicker:ColorPickerWheel.Indicator>
  <Grid>
    <Path VerticalAlignment="Top"
          HorizontalAlignment="Center"
          Fill="#aa000000"
          Stroke="#99000000"
          StrokeThickness="4">
      <Path.Data>
        <GeometryGroup>
          <EllipseGeometry Center="50, 80"
                           RadiusX="60"
                           RadiusY="60" />
        </GeometryGroup>
      </Path.Data>
    </Path>
  </Grid>
</colorpicker:ColorPickerWheel.Indicator>
```

Let me know if this works for you or not.

**Comment by porrey** [comment]
I created a branch called Uno and published a pre-release version of the NuGet package.

**Comment by ParthMandalia** [comment]
> I created a branch called Uno and published a pre-release version of the NuGet package.

The Solution I created was just limited to Uno Uwp project. In order to run all the platform in Uno, i.e. Android, Uwp, Wasm and IOS, I have created a new Uno class library solution with all the required references for Uno. I don't have any experience in developing the Class Library.

**Comment by ParthMandalia** [comment]
Sorry I didn't knew how to update the fork with your changes and committed Merge in your Master branch. Don't merge it.

**Pull request closed without merging**
